package java_test

import (
	"context"
	"path"
	"testing"

	"github.com/quay/claircore"
	"github.com/quay/claircore/java"
	"github.com/quay/claircore/test"
)

// TestScan runs the java scanner over some layers known to have java
// packages installed.
func TestScan(t *testing.T) {
	ctx, done := context.WithCancel(context.Background())
	defer done()
	for _, tc := range scanTable {
		t.Run(path.Base(tc.Name), tc.Run(ctx))
	}
}

var scanTable = []test.ScannerTestcase{
	{
		Domain: "docker.io",
		Name:   "springio/gs-spring-boot-docker",
		Hash:   "sha256:1dfab6926c5aff0b800ad764b9b9d82a84b2c4a7922bc49e736c367459e44b8d",
		Want: []*claircore.Package{
			&claircore.Package{
				Name:           "com.fasterxml:classmate",
				Version:        "1.5.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:app/libs/classmate-1.5.1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.hibernate.validator:hibernate-validator",
				Version:        "6.0.18.Final",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:app/libs/hibernate-validator-6.0.18.Final.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.fasterxml.jackson.core:jackson-annotations",
				Version:        "2.10.0",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:app/libs/jackson-annotations-2.10.0.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.fasterxml.jackson.core:jackson-core",
				Version:        "2.10.0",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:app/libs/jackson-core-2.10.0.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.fasterxml.jackson.core:jackson-databind",
				Version:        "2.10.0",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:app/libs/jackson-databind-2.10.0.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.fasterxml.jackson.datatype:jackson-datatype-jdk8",
				Version:        "2.10.0",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:app/libs/jackson-datatype-jdk8-2.10.0.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.fasterxml.jackson.datatype:jackson-datatype-jsr310",
				Version:        "2.10.0",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:app/libs/jackson-datatype-jsr310-2.10.0.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.fasterxml.jackson.module:jackson-module-parameter-names",
				Version:        "2.10.0",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:app/libs/jackson-module-parameter-names-2.10.0.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "jakarta.annotation:jakarta.annotation-api",
				Version:        "1.3.5",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:app/libs/jakarta.annotation-api-1.3.5.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "jakarta.validation:jakarta.validation-api",
				Version:        "2.0.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:app/libs/jakarta.validation-api-2.0.1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jboss.logging:jboss-logging",
				Version:        "3.4.1.Final",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:app/libs/jboss-logging-3.4.1.Final.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.slf4j:jul-to-slf4j",
				Version:        "1.7.29",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:app/libs/jul-to-slf4j-1.7.29.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.apache.logging.log4j:log4j-api",
				Version:        "2.12.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:app/libs/log4j-api-2.12.1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.apache.logging.log4j:log4j-to-slf4j",
				Version:        "2.12.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:app/libs/log4j-to-slf4j-2.12.1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "ch.qos.logback:logback-classic",
				Version:        "1.2.3",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:app/libs/logback-classic-1.2.3.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "ch.qos.logback:logback-core",
				Version:        "1.2.3",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:app/libs/logback-core-1.2.3.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.slf4j:slf4j-api",
				Version:        "1.7.29",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:app/libs/slf4j-api-1.7.29.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.yaml:snakeyaml",
				Version:        "1.25",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:app/libs/snakeyaml-1.25.jar",
				RepositoryHint: java.Repository.URI,
			},
		},
		Scanner: &java.Scanner{},
	},
	{
		Domain: "docker.io",
		Name:   "tinkerpop/gremlin-console",
		Hash:   "sha256:e6e10dd7da4509f51dbdaf50f9d786f4ca0096ba14bfa7443f19d032e35f73f7",
		Want: []*claircore.Package{
			&claircore.Package{
				Name:           "org.apache.tinkerpop:gremlin-groovy",
				Version:        "3.4.8",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/ext/gremlin-groovy/lib/gremlin-groovy-3.4.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.apache.tinkerpop:gremlin-groovy",
				Version:        "3.4.8",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/ext/gremlin-groovy/plugin/gremlin-groovy-3.4.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.apache.tinkerpop:tinkergraph-gremlin",
				Version:        "3.4.8",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/ext/tinkergraph-gremlin/lib/tinkergraph-gremlin-3.4.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.apache.tinkerpop:tinkergraph-gremlin",
				Version:        "3.4.8",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/ext/tinkergraph-gremlin/plugin/tinkergraph-gremlin-3.4.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "commons-codec:commons-codec",
				Version:        "1.14",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/commons-codec-1.14.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "commons-collections:commons-collections",
				Version:        "3.2.2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/commons-collections-3.2.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "commons-configuration:commons-configuration",
				Version:        "1.10",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/commons-configuration-1.10.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "commons-lang:commons-lang",
				Version:        "2.6",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/commons-lang-2.6.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.apache.commons:commons-lang3",
				Version:        "3.8.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/commons-lang3-3.8.1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "commons-logging:commons-logging",
				Version:        "1.2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/commons-logging-1.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "net.objecthunter:exp4j",
				Version:        "0.4.8",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/exp4j-0.4.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.apache.tinkerpop:gremlin-console",
				Version:        "3.4.8",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/gremlin-console-3.4.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.apache.tinkerpop:gremlin-core",
				Version:        "3.4.8",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/gremlin-core-3.4.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.apache.tinkerpop:gremlin-driver",
				Version:        "3.4.8",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/gremlin-driver-3.4.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.apache.tinkerpop:gremlin-shaded",
				Version:        "3.4.8",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/gremlin-shaded-3.4.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.esotericsoftware:kryo-shaded",
				Version:        "3.0.3",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/gremlin-shaded-3.4.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.esotericsoftware:reflectasm",
				Version:        "1.10.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/gremlin-shaded-3.4.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.esotericsoftware:minlog",
				Version:        "1.3.0",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/gremlin-shaded-3.4.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.fasterxml.jackson.core:jackson-databind",
				Version:        "2.9.10.5",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/gremlin-shaded-3.4.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.fasterxml.jackson.core:jackson-annotations",
				Version:        "2.9.10",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/gremlin-shaded-3.4.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.fasterxml.jackson.core:jackson-core",
				Version:        "2.9.10",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/gremlin-shaded-3.4.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.carrotsearch:hppc",
				Version:        "0.7.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/hppc-0.7.1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.apache.httpcomponents:httpclient",
				Version:        "4.5.8",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/httpclient-4.5.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.apache.httpcomponents:httpcore",
				Version:        "4.4.11",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/httpcore-4.4.11.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.squareup:javapoet",
				Version:        "1.8.0",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/javapoet-1.8.0.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.javatuples:javatuples",
				Version:        "1.2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/javatuples-1.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.mindrot:jbcrypt",
				Version:        "0.4",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/jbcrypt-0.4.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.jcabi:jcabi-log",
				Version:        "0.14",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/jcabi-log-0.14.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.jcabi:jcabi-manifests",
				Version:        "1.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/jcabi-manifests-1.1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.slf4j:jcl-over-slf4j",
				Version:        "1.7.25",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/jcl-over-slf4j-1.7.25.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "jline:jline",
				Version:        "2.14.6",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/jline-2.14.6.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "log4j:log4j",
				Version:        "1.2.17",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/log4j-1.2.17.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "io.netty:netty-all",
				Version:        "4.1.49.Final",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/netty-all-4.1.49.Final.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.slf4j:slf4j-api",
				Version:        "1.7.25",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/slf4j-api-1.7.25.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.slf4j:slf4j-log4j12",
				Version:        "1.7.25",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/slf4j-log4j12-1.7.25.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.yaml:snakeyaml",
				Version:        "1.15",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:opt/gremlin-console/lib/snakeyaml-1.15.jar",
				RepositoryHint: java.Repository.URI,
			},
		},
		Scanner: &java.Scanner{},
	},
	{
		Domain: "docker.io",
		Name:   "jenkins/jenkins",
		Hash:   "sha256:f7fc83e75d1c75b8591d9f8209ca683f47a37baefec2ed4f315898602faa8564",
		Want: []*claircore.Package{
			&claircore.Package{
				Name:           "org.jenkins-ci.main:jenkins-war",
				Version:        "2.249.2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.sun.mail:jakarta.mail",
				Version:        "1.6.5",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jakarta.mail-1.6.5.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.kohsuke.stapler:stapler-adjunct-zeroclipboard",
				Version:        "1.3.5-1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/stapler-adjunct-zeroclipboard-1.3.5-1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.fusesource.hawtjni:hawtjni-runtime",
				Version:        "1.8",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jansi-1.11.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.fusesource.jansi:jansi-native",
				Version:        "1.5",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jansi-1.11.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.fusesource.jansi:jansi",
				Version:        "1.11",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jansi-1.11.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "commons-codec:commons-codec",
				Version:        "1.14",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/commons-codec-1.14.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.kohsuke.stapler:stapler-jelly",
				Version:        "1.260",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/stapler-jelly-1.260.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci:version-number",
				Version:        "1.7",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/version-number-1.7.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.slf4j:jcl-over-slf4j",
				Version:        "1.7.26",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jcl-over-slf4j-1.7.26.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.acegisecurity:acegi-security",
				Version:        "1.0.7",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/acegi-security-1.0.7.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.kohsuke.stapler:json-lib",
				Version:        "2.4-jenkins-2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/json-lib-2.4-jenkins-2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "commons-collections:commons-collections",
				Version:        "3.2.2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/commons-collections-3.2.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jvnet.hudson:xstream",
				Version:        "1.4.7-jenkins-1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/xstream-1.4.7-jenkins-1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci:constant-pool-scanner",
				Version:        "1.2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/constant-pool-scanner-1.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci:crypto-util",
				Version:        "1.5",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/crypto-util-1.5.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci:commons-jelly",
				Version:        "1.1-jenkins-20120928",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/commons-jelly-1.1-jenkins-20120928.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci:commons-jexl",
				Version:        "1.1-jenkins-20111212",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/commons-jexl-1.1-jenkins-20111212.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.apache.sshd:sshd-core",
				Version:        "1.7.0",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/sshd-core-1.7.0.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci:memory-monitor",
				Version:        "1.9",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/memory-monitor-1.9.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci.modules:launchd-slave-installer",
				Version:        "1.2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/launchd-slave-installer-1.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci:task-reactor",
				Version:        "1.5",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/task-reactor-1.5.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jvnet.localizer:localizer",
				Version:        "1.26",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/localizer-1.26.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.kohsuke:windows-package-checker",
				Version:        "1.2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/windows-package-checker-1.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci.ui:bootstrap",
				Version:        "1.3.2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/bootstrap-1.3.2-core-assets.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.kohsuke.stapler:stapler-jrebel",
				Version:        "1.260",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/stapler-jrebel-1.260.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "commons-beanutils:commons-beanutils",
				Version:        "1.9.3",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/commons-beanutils-1.9.3.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.kohsuke.stapler:stapler",
				Version:        "1.260",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/stapler-1.260.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.slf4j:slf4j-api",
				Version:        "1.7.26",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/slf4j-api-1.7.26.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.kohsuke:libzfs",
				Version:        "0.8",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/libzfs-0.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "net.i2p.crypto:eddsa",
				Version:        "0.3.0",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/eddsa-0.3.0.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.github.jnr:jnr-posix",
				Version:        "3.0.45",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jnr-posix-3.0.45.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.kohsuke:access-modifier-annotation",
				Version:        "1.16",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/access-modifier-annotation-1.16.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.apache.commons:commons-compress",
				Version:        "1.19",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/commons-compress-1.19.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "io.jenkins.stapler:jenkins-stapler-support",
				Version:        "1.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jenkins-stapler-support-1.1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "javax.annotation:javax.annotation-api",
				Version:        "1.2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/javax.annotation-api-1.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.sun.xml.txw2:txw2",
				Version:        "20110809",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/txw2-20110809.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "commons-io:commons-io",
				Version:        "2.6",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/commons-io-2.6.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.jcraft:jzlib",
				Version:        "1.1.3-kohsuke-1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jzlib-1.1.3-kohsuke-1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jfree:jcommon",
				Version:        "1.0.23",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jcommon-1.0.23.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci.modules:instance-identity",
				Version:        "2.2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/instance-identity-2.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.sun.solaris:embedded_su4j",
				Version:        "1.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/embedded_su4j-1.1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci:annotation-indexer",
				Version:        "1.12",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/annotation-indexer-1.12.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci.modules:systemd-slave-installer",
				Version:        "1.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/systemd-slave-installer-1.1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci.main:cli",
				Version:        "2.249.2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/cli-2.249.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci:annotation-indexer",
				Version:        "1.12",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/cli-2.249.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "commons-io:commons-io",
				Version:        "2.6",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/cli-2.249.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jvnet.localizer:localizer",
				Version:        "1.26",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/cli-2.249.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.apache.sshd:sshd-core",
				Version:        "1.7.0",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/cli-2.249.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.slf4j:slf4j-api",
				Version:        "1.7.26",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/cli-2.249.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "net.i2p.crypto:eddsa",
				Version:        "0.3.0",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/cli-2.249.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.slf4j:slf4j-jdk14",
				Version:        "1.7.26",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/cli-2.249.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.glassfish.tyrus.bundles:tyrus-standalone-client-jdk",
				Version:        "1.12",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/cli-2.249.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.glassfish.tyrus:tyrus-client",
				Version:        "1.12",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/cli-2.249.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.glassfish.tyrus:tyrus-core",
				Version:        "1.12",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/cli-2.249.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.glassfish.tyrus:tyrus-spi",
				Version:        "1.12",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/cli-2.249.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "javax.websocket:javax.websocket-api",
				Version:        "1.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/cli-2.249.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.glassfish.tyrus:tyrus-container-jdk-client",
				Version:        "1.12",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/cli-2.249.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "javax.websocket:javax.websocket-client-api",
				Version:        "1.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/cli-2.249.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "commons-lang:commons-lang",
				Version:        "2.6",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/cli-2.249.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jfree:jfreechart",
				Version:        "1.0.19",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jfreechart-1.0.19.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "commons-fileupload:commons-fileupload",
				Version:        "1.3.1-jenkins-2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/commons-fileupload-1.3.1-jenkins-2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci:winstone",
				Version:        "5.10",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty:jetty-server",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "javax.servlet:javax.servlet-api",
				Version:        "3.1.0",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty:jetty-http",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty:jetty-io",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty:jetty-util",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty:jetty-servlet",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty:jetty-security",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty:jetty-webapp",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty:jetty-xml",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty.http2:http2-server",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty.http2:http2-common",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty.http2:http2-hpack",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty:jetty-alpn-server",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty.alpn:alpn-api",
				Version:        "1.1.3.v20160715",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty:jetty-jmx",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty.websocket:websocket-server",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty.websocket:websocket-common",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty.websocket:websocket-api",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty.websocket:websocket-client",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty:jetty-client",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.eclipse.jetty.websocket:websocket-servlet",
				Version:        "9.4.30.v20200611",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "io.jenkins.lib:support-log-formatter",
				Version:        "1.0",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@winstone.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci.main:remoting",
				Version:        "4.5",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/remoting-4.5.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.glassfish.tyrus.bundles:tyrus-standalone-client-jdk",
				Version:        "1.12",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/remoting-4.5.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.glassfish.tyrus:tyrus-client",
				Version:        "1.12",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/remoting-4.5.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.glassfish.tyrus:tyrus-core",
				Version:        "1.12",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/remoting-4.5.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.glassfish.tyrus:tyrus-spi",
				Version:        "1.12",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/remoting-4.5.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "javax.websocket:javax.websocket-api",
				Version:        "1.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/remoting-4.5.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.glassfish.tyrus:tyrus-container-jdk-client",
				Version:        "1.12",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/remoting-4.5.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "javax.websocket:javax.websocket-client-api",
				Version:        "1.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/remoting-4.5.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "args4j:args4j",
				Version:        "2.33",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/remoting-4.5.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci:constant-pool-scanner",
				Version:        "1.2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/remoting-4.5.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci:bytecode-compatibility-transformer",
				Version:        "2.0-beta-2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/bytecode-compatibility-transformer-2.0-beta-2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.kohsuke.jinterop:j-interop",
				Version:        "2.0.6-kohsuke-1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/j-interop-2.0.6-kohsuke-1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jruby.ext.posix:jna-posix",
				Version:        "1.0.3-jenkins-1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jna-posix-1.0.3-jenkins-1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.kohsuke.stapler:stapler-adjunct-timeline",
				Version:        "1.5",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/stapler-adjunct-timeline-1.5.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci.modules:windows-slave-installer",
				Version:        "2.0",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/windows-slave-installer-2.0.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api",
				Version:        "1.2.7",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jakarta.servlet.jsp.jstl-api-1.2.7.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci.modules:ssh-cli-auth",
				Version:        "1.8",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/ssh-cli-auth-1.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.kohsuke.jinterop:j-interopdeps",
				Version:        "2.0.6-kohsuke-1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/j-interopdeps-2.0.6-kohsuke-1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.github.jnr:jnr-x86asm",
				Version:        "1.0.2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jnr-x86asm-1.0.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.kohsuke.stapler:stapler-adjunct-codemirror",
				Version:        "1.3",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/stapler-adjunct-codemirror-1.3.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci.ui:jquery-detached",
				Version:        "1.2.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jquery-detached-1.2.1-core-assets.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "commons-digester:commons-digester",
				Version:        "2.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/commons-digester-2.1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.slf4j:slf4j-jdk14",
				Version:        "1.7.26",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/slf4j-jdk14-1.7.26.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.kohsuke:asm6",
				Version:        "6.2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/asm6-6.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.slf4j:log4j-over-slf4j",
				Version:        "1.7.26",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/log4j-over-slf4j-1.7.26.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "net.sf.ezmorph:ezmorph",
				Version:        "1.0.6",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/ezmorph-1.0.6.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "io.github.stephenc.crypto:self-signed-cert-generator",
				Version:        "1.0.0",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/self-signed-cert-generator-1.0.0.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "net.java.sezpoz:sezpoz",
				Version:        "1.13",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/sezpoz-1.13.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jvnet.robust-http-client:robust-http-client",
				Version:        "1.2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/robust-http-client-1.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.kohsuke:libpam4j",
				Version:        "1.11",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/libpam4j-1.11.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "commons-httpclient:commons-httpclient",
				Version:        "3.1-jenkins-1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/commons-httpclient-3.1-jenkins-1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jvnet.hudson:commons-jelly-tags-define",
				Version:        "1.0.1-hudson-20071021",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/commons-jelly-tags-define-1.0.1-hudson-20071021.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.github.jnr:jnr-ffi",
				Version:        "2.1.8",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jnr-ffi-2.1.8.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "jline:jline",
				Version:        "2.12",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jline-2.12.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci:symbol-annotation",
				Version:        "1.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/symbol-annotation-1.1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.samba.jcifs:jcifs",
				Version:        "1.3.17-kohsuke-1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jcifs-1.3.17-kohsuke-1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.kohsuke.stapler:stapler-groovy",
				Version:        "1.260",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/stapler-groovy-1.260.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jvnet:tiger-types",
				Version:        "2.2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/tiger-types-2.2.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci.modules:sshd",
				Version:        "2.6",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/sshd-2.6.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "commons-lang:commons-lang",
				Version:        "2.6",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/commons-lang-2.6.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.google.guava:guava",
				Version:        "11.0.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/guava-11.0.1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.kohsuke:akuma",
				Version:        "1.10",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/akuma-1.10.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci.ui:handlebars",
				Version:        "1.1.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/handlebars-1.1.1-core-assets.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci.modules:slave-installer",
				Version:        "1.7",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/slave-installer-1.7.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.github.jnr:jffi",
				Version:        "1.2.17",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jffi-1.2.17.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci.plugins.icon-shim:icon-set",
				Version:        "1.0.5",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/icon-set-1.0.5.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "args4j:args4j",
				Version:        "2.33",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/args4j-2.33.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci.modules:upstart-slave-installer",
				Version:        "1.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/upstart-slave-installer-1.1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.infradna.tool:bridge-method-annotation",
				Version:        "1.13",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/bridge-method-annotation-1.13.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.github.jnr:jnr-constants",
				Version:        "0.9.9",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jnr-constants-0.9.9.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "com.sun.activation:jakarta.activation",
				Version:        "1.2.1",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jakarta.activation-1.2.1.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jvnet.winp:winp",
				Version:        "1.28",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/winp-1.28.jar",
				RepositoryHint: java.Repository.URI,
			},
			&claircore.Package{
				Name:           "org.jenkins-ci.main:jenkins-core",
				Version:        "2.249.2",
				Kind:           claircore.BINARY,
				PackageDB:      "maven:usr/share/jenkins/jenkins.war@WEB-INF/lib/jenkins-core-2.249.2.jar",
				RepositoryHint: java.Repository.URI,
			},
		},
		Scanner: &java.Scanner{},
	},
}
